typescript: true

commandMakeDir: bin/semo/commands
pluginMakeDir: bin/semo/plugins
extendMakeDir: bin/semo/extends
scriptMakeDir: bin/semo/scripts
hookMakeDir: bin/semo/hooks

commandDir: built/bin/semo/commands
pluginDir: built/bin/semo/plugins
extendDir: built/bin/semo/extends
scriptDir: built/bin/semo/scripts
hookDir: built/bin/semo/hooks

